### ISSUE TITLE
max_columns

### ISSUE THREAD

**Issue by SohumB** [uberVU/grid#45]
So we'll shortly be looking at implementing a `max_columns` for `grid` (we've been looking for grid implementations that have both `max_rows` and `max_columns` for a while now :p). How close is it to being implementable? Any tips would also be super useful.

Thanks!

**Comment by stefanhendriks** [comment]
+1

**Comment by andrei-picus-hs** [comment]
Progress for this is tracked in https://github.com/uberVU/grid/issues/62.
