### ISSUE TITLE
Remove Drag

### ISSUE THREAD

**Issue by dasilvans** [uberVU/grid#49]
Any "clean" way to disable drag and drop in all the elements?
Thanks!! keep up the great work.

**Comment by skidding** [comment]
Yes, there's a `dragAndDrop` option that [defaults to true](https://github.com/uberVU/grid/blob/master/src/jquery.gridList.js#L27). Set it as `false` in the options you send to the plugin.

**Comment by dasilvans** [comment]
Thanks for the support and amazing library.
