### ISSUE TITLE
How is it responsive?

### ISSUE THREAD

**Issue by LulzAugusto** [uberVU/grid#58]
I don't know if I understood correctly what the README says, maybe I'm missing something, but how the grid would possibly be responsive if the items width and height are based onde the container? Do I have to set a fixed height to the container? 

I'm asking because I'm trying to make a few samples and it always appear with the same size, no matter the screen width or height.

**Comment by skidding** [comment]
It's responsive to the parent container, not the window.

![responsive-grid](https://cloud.githubusercontent.com/assets/250750/8104328/977e02c2-1038-11e5-9d8c-9b1bd22425f2.gif)

**Comment by LulzAugusto** [comment]
Hello @skidding. Thanks for your help.

So do you set a fixed height to the parent container?

**Comment by skidding** [comment]
Yes, and we set a custom window resize handler. This is how the demo does it: https://github.com/uberVU/grid/blob/master/demo/load.js#L30-L35

**Comment by LulzAugusto** [comment]
Thanks. I got it now.
